version: '3'

services:
  backend-to-api:
    image: yangclivia/pandora-to-api:0.7.8
    restart: always
    ports:
      - "33333:33333"
    volumes:
      - ./log:/app/log
      - ./images:/app/images
      - ./data:/app/data
      - ./files:/app/files
    environment:
      - TZ=Asia/Shanghai
      
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
